version: '3.8'

services:
  api:
    build: .
    container_name: bodybliss-api
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: bodybliss-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bodybliss
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bodybliss-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
